# Funding options for Keplear
# Uncomment and configure if you want to enable GitHub Sponsors

# github: [yourusername]
# patreon: yourusername
# ko_fi: yourusername
# custom: ["https://yourwebsite.com/donate"]
